meta_product_name: "InkFinder"
meta_title: "InkFinder • You won't regret that one!"
meta_description: "InkFinder facilitates your tattoo journey with personalized inspiration and guidance finding the right artist for a tattoo you won't regret!"
meta_image: "map_icon.png"

